apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: andi
  name: andi
spec:
  replicas: 10
  selector:
    matchLabels:
      app: andi
  template:
    metadata:
      labels:
        app: andi
    spec:
      containers:
        - image: httpd:alpine3.19
          name: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

