apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mealy
  name: mealy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mealy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
