apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealy
  name: mealy
  namespace: andy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealy
  strategy: {}
  template:
    metadata:
      labels:
        app: mealy
    spec:
      containers:
        - image: ghcr.io/mealie-recipes/mealie:v1.2.0
          name: mealie
          ports: 
            - containerPort: 9000
